# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "flame_channel_parser"
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julik Tarkhanov"]
  s.date = "2011-11-21"
  s.description = "Reads and interpolates animation channels in IFFS setups"
  s.email = "me@julik.nl"
  s.executables = ["bake_flame_channel", "bake_flame_timewarp"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".travis.yml",
    "Gemfile",
    "History.txt",
    "README.rdoc",
    "Rakefile",
    "bin/bake_flame_channel",
    "bin/bake_flame_timewarp",
    "flame_channel_parser.gemspec",
    "lib/channel.rb",
    "lib/extractor.rb",
    "lib/flame_channel_parser.rb",
    "lib/interpolator.rb",
    "lib/key.rb",
    "lib/parser.rb",
    "lib/segments.rb",
    "lib/timewarp_extractor.rb",
    "test/channel_with_constants.dat",
    "test/sample_channel.dat",
    "test/snaps/Cycle_and_revcycle.action",
    "test/snaps/FLEM_BrokenTangents.action",
    "test/snaps/FLEM_advanced_curve.png",
    "test/snaps/FLEM_advanced_curve_example_FL2012.action",
    "test/snaps/FLEM_baked_curve.png",
    "test/snaps/FLEM_curves_example.action",
    "test/snaps/FLEM_curves_example_migrated_to_2012.action",
    "test/snaps/FLEM_std_curve.png",
    "test/snaps/RefT_Steadicam.timewarp",
    "test/snaps/RefT_Steadicam_Baked.timewarp",
    "test/snaps/RefT_Steadicam_Extraction.txt",
    "test/snaps/RefT_Steadicam_Extraction_F19_to_347.txt",
    "test/snaps/RefT_Steadicam_TwoKFs.timewarp",
    "test/snaps/RefT_Steadicam_TwoKFs_AnotherSlope.timewarp",
    "test/snaps/RefT_Steadicam_TwoKFs_HermiteAtBegin.timewarp",
    "test/snaps/TW.timewarp",
    "test/snaps/TW_015_010_v03.timewarp",
    "test/snaps/TW_SingleFrameExtrapolated_from2011.timewarp",
    "test/snaps/TW_TEST.F_Kronos",
    "test/snaps/timewarp_where_interp_fails_at_end.timewarp",
    "test/test_channel.rb",
    "test/test_cli.rb",
    "test/test_cli_timewarp_extractor.rb",
    "test/test_extractor.rb",
    "test/test_flame_channel_parser.rb",
    "test/test_interpolator.rb",
    "test/test_key.rb",
    "test/test_segments.rb",
    "test/test_timewarp_extractor.rb",
    "test/timewarp_examples/TW_015_010_v01_Baked.timewarp",
    "test/timewarp_examples/TW_016_010_v01.timewarp",
    "test/timewarp_examples/TW_016_010_v01_Baked.timewarp",
    "test/timewarp_examples/TW_16_010_v01.output.txt",
    "test/timewarp_examples/TW_TEST.F_Kronos",
    "test/timewarp_examples/output.txt"
  ]
  s.homepage = "http://guerilla-di.org/flame-channel-parser/"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A parser/interpolator for Flame/Smoke animation curves"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<flame_channel_parser>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<cli_test>, ["~> 1.0"])
      s.add_runtime_dependency(%q<update_hints>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<cli_test>, ["~> 1.0"])
    else
      s.add_dependency(%q<flame_channel_parser>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<cli_test>, ["~> 1.0"])
      s.add_dependency(%q<update_hints>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<cli_test>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<flame_channel_parser>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<cli_test>, ["~> 1.0"])
    s.add_dependency(%q<update_hints>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<cli_test>, ["~> 1.0"])
  end
end

